"""add unique constraint to coupon transactions

Revision ID: 0eb5ae2f9496
Revises: add_auto_update_runs
Create Date: 2026-02-04 10:19:00.145841

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0eb5ae2f9496'
down_revision = 'add_auto_update_runs'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_email_status')
    op.drop_table('bot_settings')
    op.drop_table('notification_settings')
    op.drop_table('telegram_users_audit_log')
    with op.batch_alter_table('admin_messages', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('auto_update_runs', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'running'::character varying"))
        batch_op.alter_column('updated_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('failed_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('skipped_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('job_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_index('ix_auto_update_runs_started_at')
        batch_op.drop_index('ix_auto_update_runs_status')
        batch_op.drop_constraint('auto_update_runs_triggered_by_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('triggered_by_user_id')
        batch_op.drop_column('run_type')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('image_path',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               nullable=False)

    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('expiration',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using="expiration::date")
        batch_op.alter_column('date_added',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('exclude_saving',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('auto_download_details',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('cvv',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('card_exp',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('last_detail_view',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when user last \n  viewed coupon detail page',
               existing_nullable=True)
        batch_op.alter_column('last_company_view',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when user last \n  clicked on company card from main page',
               existing_nullable=True)
        batch_op.alter_column('last_code_view',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when user last \n  clicked show code button',
               existing_nullable=True)
        batch_op.alter_column('last_scraped',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp of the last time this \n  coupon was scraped for data updates',
               existing_nullable=True)
        batch_op.drop_index('idx_coupon_company_display_order')
        batch_op.drop_index('idx_coupon_last_scraped')
        batch_op.drop_index('idx_coupon_widget_display_order', postgresql_where='(widget_display_order IS NOT NULL)')
        batch_op.create_unique_constraint(None, ['code'])
        batch_op.drop_constraint('fk_company', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('special_message')
        batch_op.drop_column('reminder_sent_today')
        batch_op.drop_column('company_display_order')
        batch_op.drop_column('company_id')
        batch_op.drop_column('discount_percentage')
        batch_op.drop_column('widget_display_order')
        batch_op.drop_column('show_in_widget')

    with op.batch_alter_table('coupon_requests', schema=None) as batch_op:
        batch_op.alter_column('other_company',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('value',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('cost',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('date_requested',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint('coupon_requests_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('is_available')
        batch_op.drop_column('used_value')
        batch_op.drop_column('status')
        batch_op.drop_column('is_one_time')

    with op.batch_alter_table('coupon_tags', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'coupon', ['coupon_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'tag', ['tag_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('coupon_transaction', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_coupon_transaction_ref', ['coupon_id', 'reference_number'])

    with op.batch_alter_table('coupon_usage', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'coupon', ['coupon_id'], ['id'])

    with op.batch_alter_table('feature_access', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('newsletters', schema=None) as batch_op:
        batch_op.drop_column('greeting_content')
        batch_op.drop_column('footer_message')
        batch_op.drop_column('highlight_icon')
        batch_op.drop_column('greeting_title')

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.alter_column('count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('telegram_users', schema=None) as batch_op:
        batch_op.alter_column('verification_token',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=True)
        batch_op.alter_column('verification_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.drop_index('idx_telegram_users_telegram_chat_id')
        batch_op.drop_index('idx_telegram_users_user_id')
        batch_op.drop_index('idx_telegram_users_verification_token')
        batch_op.drop_constraint('telegram_users_user_hash_key', type_='unique')
        batch_op.drop_constraint('telegram_users_user_id_telegram_chat_id_key', type_='unique')
        batch_op.drop_column('disconnected_at')
        batch_op.drop_column('user_hash')
        batch_op.drop_column('is_disconnected')

    with op.batch_alter_table('user_activities', schema=None) as batch_op:
        batch_op.alter_column('extra_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.drop_constraint('user_activities_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('region')
        batch_op.drop_column('country')
        batch_op.drop_column('timezone')
        batch_op.drop_column('isp')
        batch_op.drop_column('lat')
        batch_op.drop_column('org')
        batch_op.drop_column('zip')
        batch_op.drop_column('city')
        batch_op.drop_column('lon')
        batch_op.drop_column('country_code')
        batch_op.drop_column('as_info')

    with op.batch_alter_table('user_consents', schema=None) as batch_op:
        batch_op.drop_index('idx_user_consents_timestamp')
        batch_op.drop_index('idx_user_consents_user_id')
        batch_op.drop_constraint('user_consents_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('user_reviews', schema=None) as batch_op:
        batch_op.drop_index('idx_user_reviews_reviewed_user_id')
        batch_op.drop_index('idx_user_reviews_reviewer_id')
        batch_op.drop_constraint('user_reviews_reviewed_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('user_reviews_reviewer_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'transactions', ['coffee_transaction'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['reviewed_user_id'], ['id'])
        batch_op.create_foreign_key(None, 'transactions', ['transaction_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['reviewer_id'], ['id'])

    with op.batch_alter_table('user_tour_progress', schema=None) as batch_op:
        batch_op.drop_index('user_tour_progress_user_id_key')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('google_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('profile_image',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('dismissed_expiring_alert_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('region')
        batch_op.drop_column('push_token')
        batch_op.drop_column('allow_widget_access')
        batch_op.drop_column('newsletter_image')
        batch_op.drop_column('coupons_sold_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coupons_sold_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('newsletter_image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('allow_widget_access', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True, comment="Grants permission for the homescreen widget to access this user's data."))
        batch_op.add_column(sa.Column('push_token', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('region', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('dismissed_expiring_alert_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('profile_image',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('google_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('user_tour_progress', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('user_tour_progress_user_id_key', ['user_id'], unique=True)

    with op.batch_alter_table('user_reviews', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_reviews_reviewer_id_fkey', 'users', ['reviewer_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key('user_reviews_reviewed_user_id_fkey', 'users', ['reviewed_user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('idx_user_reviews_reviewer_id', ['reviewer_id'], unique=False)
        batch_op.create_index('idx_user_reviews_reviewed_user_id', ['reviewed_user_id'], unique=False)

    with op.batch_alter_table('user_consents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_consents_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('idx_user_consents_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_user_consents_timestamp', ['timestamp'], unique=False)

    with op.batch_alter_table('user_activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('as_info', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('country_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('zip', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('org', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('isp', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('region', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_activities_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('extra_metadata',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('telegram_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_disconnected', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('disconnected_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('telegram_users_user_id_telegram_chat_id_key', ['user_id', 'telegram_chat_id'])
        batch_op.create_unique_constraint('telegram_users_user_hash_key', ['user_hash'])
        batch_op.create_index('idx_telegram_users_verification_token', ['verification_token'], unique=False)
        batch_op.create_index('idx_telegram_users_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_telegram_users_telegram_chat_id', ['telegram_chat_id'], unique=False)
        batch_op.alter_column('verification_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
        batch_op.alter_column('verification_token',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('count',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('newsletters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('greeting_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('highlight_icon', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('footer_message', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('greeting_content', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('feature_access', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('coupon_usage', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('coupon_transaction', schema=None) as batch_op:
        batch_op.drop_constraint('uq_coupon_transaction_ref', type_='unique')

    with op.batch_alter_table('coupon_tags', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('coupon_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_one_time', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'פעיל'::character varying"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('used_value', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('0.0'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_available', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('coupon_requests_user_id_fkey', 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('date_requested',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('cost',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('value',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0.00'))
        batch_op.alter_column('other_company',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('show_in_widget', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True, comment='Flag to indicate if the coupon should be shown in the widget.'))
        batch_op.add_column(sa.Column('widget_display_order', sa.INTEGER(), autoincrement=False, nullable=True, comment="מיקום הקופון בווידג'ט (1-4), NULL אם לא מוצג בווידג'ט"))
        batch_op.add_column(sa.Column('discount_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('company_display_order', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('reminder_sent_today', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('special_message', sa.TEXT(), autoincrement=False, nullable=True, comment='Optional prominent note to show in\nthe iOS detail view.'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_company', 'companies', ['company_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index('idx_coupon_widget_display_order', ['widget_display_order'], unique=False, postgresql_where='(widget_display_order IS NOT NULL)')
        batch_op.create_index('idx_coupon_last_scraped', ['last_scraped'], unique=False)
        batch_op.create_index('idx_coupon_company_display_order', ['user_id', 'company', 'company_display_order'], unique=False)
        batch_op.alter_column('last_scraped',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp of the last time this \n  coupon was scraped for data updates',
               existing_nullable=True)
        batch_op.alter_column('last_code_view',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when user last \n  clicked show code button',
               existing_nullable=True)
        batch_op.alter_column('last_company_view',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when user last \n  clicked on company card from main page',
               existing_nullable=True)
        batch_op.alter_column('last_detail_view',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when user last \n  viewed coupon detail page',
               existing_nullable=True)
        batch_op.alter_column('card_exp',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('cvv',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('auto_download_details',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True,
               existing_server_default=sa.text('NULL::character varying'))
        batch_op.alter_column('exclude_saving',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('date_added',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('expiration',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('image_path',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('auto_update_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('run_type', sa.VARCHAR(length=50), server_default=sa.text("'manual'::character varying"), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('triggered_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('auto_update_runs_triggered_by_user_id_fkey', 'users', ['triggered_by_user_id'], ['id'])
        batch_op.create_index('ix_auto_update_runs_status', ['status'], unique=False)
        batch_op.create_index('ix_auto_update_runs_started_at', ['started_at'], unique=False)
        batch_op.alter_column('job_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('skipped_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('failed_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('updated_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'running'::character varying"))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('admin_messages', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))

    op.create_table('telegram_users_audit_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('telegram_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('changed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('changed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='telegram_users_audit_log_pkey')
    )
    op.create_table('notification_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('daily_notification_hour', sa.INTEGER(), server_default=sa.text('20'), autoincrement=False, nullable=True),
    sa.Column('daily_notification_minute', sa.INTEGER(), server_default=sa.text('14'), autoincrement=False, nullable=True),
    sa.Column('monthly_notification_hour', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=True),
    sa.Column('monthly_notification_minute', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('expiration_day_hour', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=True),
    sa.Column('expiration_day_minute', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='notification_settings_pkey')
    )
    op.create_table('bot_settings',
    sa.Column('key', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('key', name='bot_settings_pkey')
    )
    op.create_table('daily_email_status',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('process', sa.VARCHAR(length=50), server_default=sa.text("'default'::character varying"), autoincrement=False, nullable=False),
    sa.Column('was_sent', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='daily_email_status_pkey'),
    sa.UniqueConstraint('date', 'process', name='daily_email_status_date_process_key')
    )
    # ### end Alembic commands ###
