"""Add user preferences for newsletter and telegram

Revision ID: 99d197bcf7d0
Revises: f78a2e3a929a
Create Date: 2025-06-22 23:18:44.211459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99d197bcf7d0'
down_revision = 'f78a2e3a929a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('newsletter_subscription', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('users', sa.Column('telegram_monthly_summary', sa.Boolean(), nullable=False, server_default='true'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_monthly_summary')
    op.drop_column('users', 'newsletter_subscription')
    # ### end Alembic commands ###
