"""Add newsletter_type and custom_html to Newsletter model

Revision ID: add_newsletter_type_and_custom_html
Revises: add_newsletter_models
Create Date: 2025-06-22 18:45:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'newsletter_update'
down_revision = 'add_newsletter_models'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newsletters', sa.Column('custom_html', sa.Text(), nullable=True))
    op.add_column('newsletters', sa.Column('newsletter_type', sa.String(length=20), nullable=True))
    
    # Set default value for existing records
    op.execute("UPDATE newsletters SET newsletter_type = 'structured' WHERE newsletter_type IS NULL")
    
    # Make content nullable
    op.alter_column('newsletters', 'content', nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('newsletters', 'content', nullable=False)
    op.drop_column('newsletters', 'newsletter_type')
    op.drop_column('newsletters', 'custom_html')
    # ### end Alembic commands ###