"""Add strauss_coupon_url column to coupon table

Revision ID: add_strauss_coupon_url
Revises: b43b720fccd5
Create Date: 2025-08-02 08:51:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_strauss_coupon_url'
down_revision = 'b43b720fccd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strauss_coupon_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coupon', schema=None) as batch_op:
        batch_op.drop_column('strauss_coupon_url')

    # ### end Alembic commands ###