"""Add id column to user_tour_progress

Revision ID: add_id_to_user_tour_progress
Revises: f2fd28cef0de
Create Date: 2024-05-30 00:15:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "add_id_to_user_tour_progress"
down_revision = "f2fd28cef0de"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_tour_progress", schema=None) as batch_op:
        batch_op.add_column(sa.Column("id", sa.Integer(), nullable=False))
        batch_op.create_primary_key("pk_user_tour_progress", ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_tour_progress", schema=None) as batch_op:
        batch_op.drop_constraint("pk_user_tour_progress", type_="primary")
        batch_op.drop_column("id")

    # ### end Alembic commands ### 