"""Add custom titles to newsletter

Revision ID: ef0f1e525b3f
Revises: 99d197bcf7d0
Create Date: 2025-06-25 22:31:04.630877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef0f1e525b3f'
down_revision = '99d197bcf7d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('main_title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('additional_title', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newsletters', schema=None) as batch_op:
        batch_op.drop_column('additional_title')
        batch_op.drop_column('main_title')

    # ### end Alembic commands ###